apiVersion: v1
kind: Service
metadata:
  name: pug-api-svc
  labels:
    name: pug-api-svc
    app: pug-ci
spec:
  ports:
    - port: 3000
  selector:
    name: pug-api-pod
    app: pug-ci
  type: NodePort
