apiVersion: v1
kind: ReplicationController
metadata:
  name: pug-api-rc
spec:
  replicas: 1
  selector:
    name: pug-api-pod
    app: pug-ci
  template:
    metadata:
      name: pug-api-pod
      labels:
        name: pug-api-pod
        app: pug-ci
    spec:
      containers:
        - name: pug-api
          image: pug-ci/pug-api:0.1.0
          ports:
            - containerPort: 3000
