apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    name: postgres-svc
    app: pug-ci
spec:
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
  selector:
    name: postgres-pod
    app: pug-ci
