apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    name: rabbitmq-pod
    app: pug-ci
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  type: NodePort
