apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq-rc
spec:
  replicas: 1
  selector:
    name: rabbitmq-pod
    app: pug-ci
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        name: rabbitmq-pod
        app: pug-ci
    spec:
      containers:
        - name: rabbitmq
          image: pug-ci/rabbitmq:0.1.0
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /var/lib/rabbitmq
